### ISSUE TITLE
Ejercicio #1-b) Que son los sensores resistivos? Como se conectan a través de un divisor resistivo? Que es el acondicionamiento de señales?

### ISSUE THREAD

**Issue by Mauro-Martinez** [ISPC-TST-Electronica-Microcontrolada/Grupo5#22]

**Comment by ernesto0369** [comment]
[Sensores resistivos.pdf](https://github.com/ISPC-TST-Electronica-Microcontrolada/Grupo5/files/9492708/Sensores.resistivos.pdf)
[Acondicionamiento_de_sensores_resistivos.pdf](https://github.com/ISPC-TST-Electronica-Microcontrolada/Grupo5/files/9492709/Acondicionamiento_de_sensores_resistivos.pdf)
