### ISSUE TITLE
Ejercicio #2- e) Que protocolo utilizan los led ws2812? Hay alguna librería para controlarlos con módulos ESP12 o ESP32? Que se podría armar con los WS2812 y porque el fabricante no utilizo protocolos SPI, UART o I2C?

### ISSUE THREAD

**Issue by Mauro-Martinez** [ISPC-TST-Electronica-Microcontrolada/Grupo5#24]

**Comment by ernesto0369** [comment]
[WS2812 Led.pdf](https://github.com/ISPC-TST-Electronica-Microcontrolada/Grupo5/files/9492693/WS2812.Led.pdf)
[Conectar y controlar LEDs WS2812B a ESP8266 con ESPEasy.pdf](https://github.com/ISPC-TST-Electronica-Microcontrolada/Grupo5/files/9492695/Conectar.y.controlar.LEDs.WS2812B.a.ESP8266.con.ESPEasy.pdf)
