### ISSUE TITLE
Ejercicio #2- c) Como probaría si una comunicación SPI funciona correctamente en su laboratorio?

### ISSUE THREAD

**Issue by Mauro-Martinez** [ISPC-TST-Electronica-Microcontrolada/Grupo5#26]

**Comment by recursosssbb** [comment]
AHORA VEMOS QUE HACER EN EL LABORATORIO

imagen

    ANTES DE CONECTAR ASEGURAR PARAMETROS DE CONEXION PARA EVITAR AVERIAS
    UNA VEZ CONECTADOS, VERIFICAR FUNCIONAMIENTO DEL SENSOR
    VERIFICARAR TODAS LAS CONEXIONES DE CABLES
    Si estás utilizando cables relativamente largos (más de 25 cm) para conectar un dispositivo utilizando SPI con Arduino, es posible que existan problemas en la comunicación que se deben a dos factores principalmente: la velocidad de transmisión y el ruido electromagnético, Si esto te ocurre, debemos intentar utilizar cables más cortos, si esto no es posible, se debe comprobar que el sistema no esté cerca de ninguna fuente de ruido electromagnético, como pueden ser fuentes de alimentación conmutadas, radios, antenas, o incluso tu ordenador.
    VERIFICAR WIFI
    Para controlar el bus SPI con Arduino existe la librería SPI, que permite enviar y recibir datos utilizando dicho bus.
    la librería solo permite programar la placa para que funcione como maestro, y no como esclavo.
    Esta librería cuenta con dos clases QUE PODEMOS CONIGURAR
    --> SPISettings: permite establecer los parámetros de las transferencias SPI a realizar. Un objeto de esta clase puede ser utilizado para configurar el bus SPI y asi especificar: Velocidad de transferencia máxima, orden de transmisión de bits, modo de transmisión
    --> SPI: permite controlar el bus SPI para enviar y recibir información.
